[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"

[rpc_endpoints]
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
